### ISSUE TITLE
可以支持截图直接上传吗

### ISSUE THREAD

**Issue by happyCoding1024** [MatrixAges/picpic#2]
请问现在是不是只有将图片放在 asset 文件夹下，然后执行 git commit 和 git push 推送到远程仓库，才可以生成图片链接。
不能像 picgo 那样粘贴板中的截图就可以自动上传，生成链接呢？

**Comment by MatrixAge** [comment]
不支持，picgo是客户端，拥有截图的能力，picpic是代码项目，更多的可能性需要你自己解决
