### ISSUE TITLE
how do i debug locally?

### ISSUE THREAD

**Issue by flamingo-sky** [MatrixAges/picpic#4]
the pic only show a logo ,then to be blank, after open the html

**Comment by MatrixAge** [comment]
- install vscode plugin:[Open In Default Browser - peakchen90]
- confirm you assets
- npm run build
- open dist and open index.html use `Open In Default Browser`

**Comment by flamingo-sky** [comment]
thanks

**Comment by flamingo-sky** [comment]
**抱歉错误仍然存在，浏览器在屏幕中出现logo 之后一片空白，console里面也没有任何信息打印。**
环境：win10
浏览器：google浏览器
截图：
![image](https://user-images.githubusercontent.com/32033165/103631391-e23bac80-4f7d-11eb-9336-d47f908ee4a6.png)

**Comment by MatrixAge** [comment]
> **抱歉错误仍然存在，浏览器在屏幕中出现logo 之后一片空白，console里面也没有任何信息打印。**
> 环境：win10
> 浏览器：google浏览器
> 截图：
> ![image](https://user-images.githubusercontent.com/32033165/103631391-e23bac80-4f7d-11eb-9336-d47f908ee4a6.png)

直接打开是不行的，用vscode插件，在浏览器地址栏，你应该看到的是一个带端口号的地址。

**Comment by flamingo-sky** [comment]
> > **抱歉错误仍然存在，浏览器在屏幕中出现logo 之后一片空白，console里面也没有任何信息打印。**
> > 环境：win10
> > 浏览器：google浏览器
> > 截图：
> > ![image](https://user-images.githubusercontent.com/32033165/103631391-e23bac80-4f7d-11eb-9336-d47f908ee4a6.png)
> 
> 直接打开是不行的，用vscode插件，在浏览器地址栏，你应该看到的是一个带端口号的地址。

也是一样的呢，我用vscode和webstorm 都试过，不行呢，换台电脑也是不行。直接打开和插件打开应该是一样的都是纯静态页面调用js。
![image](https://user-images.githubusercontent.com/32033165/103716532-43a36000-4ffe-11eb-84a1-42325d2404a2.png)

**Comment by flamingo-sky** [comment]
> > **抱歉错误仍然存在，浏览器在屏幕中出现logo 之后一片空白，console里面也没有任何信息打印。**
> > 环境：win10
> > 浏览器：google浏览器
> > 截图：
> > ![image](https://user-images.githubusercontent.com/32033165/103631391-e23bac80-4f7d-11eb-9336-d47f908ee4a6.png)
> 
> 直接打开是不行的，用vscode插件，在浏览器地址栏，你应该看到的是一个带端口号的地址。

也是不行呢，webstorm和vscode都试过了呢，没有报错，不知该从何处入手。
![image](https://user-images.githubusercontent.com/32033165/103716957-3d61b380-4fff-11eb-87e8-d32d3e1f18f3.png)

**Comment by MatrixAge** [comment]
给个例子仓库地址 我看看

**Comment by flamingo-sky** [comment]
> 给个例子仓库地址 我看看
必须部署到github_page么，我没有部署github 和 action，本地调试。。拉取的您仓库的源代码进行的build。看来我只能一个一个函数log看一下。
![image](https://user-images.githubusercontent.com/32033165/103729642-def6fe00-501b-11eb-83d2-163fd84dfd0a.png)

**Comment by flamingo-sky** [comment]
hi,你好，我在dist/libs/js/include.js的replaceIncludeElements函数中打印 includeTals，发现数组值是空的
`var includeTals = document.getElementsByTagName('include') `
`console.log(includeTals);`
![image](https://user-images.githubusercontent.com/32033165/103750539-eaf5b680-5041-11eb-9adb-105ba3faa084.png)

**Comment by flamingo-sky** [comment]
> 你好，我在dist/libs/js/include.js的replaceIncludeElements函数中打印 includeTals，发现数组值是空的，这是正常的么
> `var includeTals = document.getElementsByTagName('include') `
> `console.log(includeTals);`
> ![image](https://user-images.githubusercontent.com/32033165/103750539-eaf5b680-5041-11eb-9adb-105ba3faa084.png)

我在知乎看到了您的帖子，编译之后好像模板没有注入进去

**Comment by MatrixAge** [comment]
为什么要用http server来浏览页面，就是因为这里面有一个使用ajax请求html模版的过程，(文章链接)[https://juejin.cn/post/6906791889777721352]，我在本地试过了，我这边是ok，你自己捋一下，为什么没有注入成功

**Comment by MatrixAge** [comment]
我把你fork出来的项目拉下来跑了一下，在我这里是没问题的，你用http-server试试看，打不开的原因应该是其他，问题核查完毕，issue关了。

**Comment by flamingo-sky** [comment]
> 为什么要用http server来浏览页面，就是因为这里面有一个使用ajax请求html模版的过程，(文章链接)[https://juejin.cn/post/6906791889777721352]，我在本地试过了，我这边是ok，你自己捋一下，为什么没有注入成功



> 我把你fork出来的项目拉下来跑了一下，在我这里是没问题的，你用http-server试试看，打不开的原因应该是其他，问题核查完毕，issue关了。

问题出在路径分隔符号，globby 在全局模式下只能用正斜杆
[https://www.npmjs.com/package/globby](url)
**Note that glob patterns can only contain forward-slashes, not backward-slashes, so if you want to construct a glob pattern from path components, you need to use path.posix.join() instead of path.join().**

**Comment by flamingo-sky** [comment]
> Note that glob patterns can only contain forward-slashes, not backward-slashes, so if you want to construct a glob pattern from path components, you need to use path.posix.join() instead of path.join().

对于windows用户path.join 得到的都是反斜杠，所以匹配不到组件文件
